name: Tests

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: testing
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, dom, fileinfo, mysql, sqlite3
          coverage: xdebug

      - name: Copy .env
        run: |
          cd backend
          php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Install Dependencies
        run: |
          cd backend
          composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Generate key
        run: |
          cd backend
          php artisan key:generate

      - name: Directory Permissions
        run: |
          cd backend
          chmod -R 755 storage bootstrap/cache

      - name: Create Database
        run: |
          cd backend
          mkdir -p database
          touch database/database.sqlite

      - name: Run Unit Tests
        run: |
          cd backend
          php artisan test --testsuite=Unit --coverage-clover coverage-unit.xml

      - name: Run Feature Tests
        run: |
          cd backend
          php artisan test --testsuite=Feature --coverage-clover coverage-feature.xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./backend/coverage-unit.xml,./backend/coverage-feature.xml
          directory: ./backend
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false
